{title: 'Board Game Night', category: this.categories[3], icon: this.icons[2], categoryColor: this.categoryColors[3], description: "Planning to play Scythe, Cosmic Encounter, and Diplomacy. Players with any level of experience are welcome."}
{title: 'Very Fun Party', category: this.categories[3], icon: this.icons[2], categoryColor: this.categoryColors[3], description: "This will be the best party ever, I assure you."}
{title: 'MAT137 Study Session', category: this.categories[0], icon: this.icons[0], categoryColor: this.categoryColors[0], description: 'Studying MAT137 in preperation for the upcoming midterm. We cannot dissapoint Alfonso.'}
{title: 'Careers in Finance - Information and Networking', category: this.categoris[2], icon: this.icons[1], categoryColor: this.categoryColors[2], description: 'Learn some very boring things about finance that will make you rich.'}
{title: 'Introduction to Machine Learning', category: this.categories[0], icon: this.icons[0], categoryColor: this.categoryColors[0], description: 'Learn the basics of neural networks! No prior knowledge required. Held in BA1160.'}
{title: 'Winter Touch Football', category: this.categories[1], icon: this.icons[3], categoryColor: this.categoryColors[1], description: 'Touch football, but with snow all over the place. These have the potential to devolve into snowball fights, which are still fun. Approximately 12 players required.'}
{title: 'CSC240 Midterm Prep', category: this.categories[0], icon: this.icons[0], categoryColor: this.categoryColors[0], description: 'A CSSU-hosted group preparation session for the CSC240 midterm. Hopefully we can get more than 4/30 on this one.'}
{title: 'Entrepreneur Meetup', category: this.categoris[2], icon: this.icons[1], categoryColor: this.categoryColors[2], description: 'A networking and knowledge sharing session for entrereneurs of Toronto.'}
{title: 'Russian Language Exchange', category: this.categories[0], icon: this.icons[0], categoryColor: this.categoryColors[0], description: 'Russian speakers learning English and English speakers learning Russian are invited to meet up and practice their language skills with each other.'}
{title: 'Community Centre Dodgeball Game', category: this.categories[1], icon: this.icons[3], categoryColor: this.categoryColors[1], description: 'Come play dodgeball at the community centre! It will be fun!'}
